name: Haskell CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt update
          sudo apt install apt-transport-https curl gnupg-agent ca-certificates software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt install docker-ce docker-ce-cli containerd.io -y
          sudo docker build -t glados .
          sudo docker run --rm -t glados /bin/bash
        shell: sh
        env:
          DOCKERHUB_USERNAME: GladosTek
          DOCKERHUB_TOKEN: dckr_pat_z1Tqr1UKRAEp-3eAIhF1W8LkXYg

      - name: Run ls -la
        run: ls -la
        
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_TOKEN

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: $DOCKER_USERNAME/glados:latest
