name: Haskell CI

on:
  push:
  pull_request:

jobs:
  build:

    name: Build Code Base
    runs-on: ubuntu-latest
    container:
      image: haskell:latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3

    - name: Build
      run: stack build

    - name: Unit Tests
      run: stack test > unit_tests_res
      
    - name: Create Artifact
      uses: actions/upload-artifact@v1
      with:
        name: unit_tests_res
        path: unit_tests_res
