name: Haskell CI

on:
  push:
  pull_request:

jobs:
  build:

    name: Build Code Base
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      run: |
        sudo apt-get install docker
        docker build -t glados .
        docker run -it glados bash
        make

    - name: Unit Tests
      run: stack test > unit_tests_res
      
    - name: Create Artifact
      uses: actions/upload-artifact@v1
      with:
        name: unit_tests_res
        path: unit_tests_res
