name: Haskell CI

on:
  push:
  pull_request:

jobs:
  build:

    name: Build Code Base
    runs-on: ubuntu-20.04
    container:
      image: haskell:latest
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3
      
    - name: Stack permissions bug workaround
      run: "chown -R $(id -un):$(id -gn) ~"
      
    - name: Install Docker
      run: |
        apt-get update
        apt-get install -Force ca-certificates curl gnupg lsb-release
        mkdir -m 0755 -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg
        gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -Force docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      run: |
        apt-get install docker
        docker build -t glados .
        docker run -it glados bash
        make

    - name: Unit Tests
      run: stack test > unit_tests_res
      
    - name: Create Artifact
      uses: actions/upload-artifact@v1
      with:
        name: unit_tests_res
        path: unit_tests_res
