name: Haskell CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build
        run: |
          sudo apt update
          sudo apt install apt-transport-https curl gnupg-agent ca-certificates software-properties-common -y
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
          sudo apt install docker-ce docker-ce-cli containerd.io -y
          sudo docker build -t glados .
          sudo docker run --rm -t glados /bin/bash
        shell: sh

      - name: Run ls -la
        run: ls -la
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: glados
          path: ./glados

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: glados
          path: ./glados

      - name: Compress project build
        run: zip -r -j glados.zip glados-artifact

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          prerelease: false

      - name: Upload Release
        id: upload_release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./glados.zip
          asset_name: glados.zip
          asset_content_type: application/zip
          token: ${{ secrets.GLADOS }}
