name: Haskell-CI

on:
  push:
  pull_request:

jobs:
  build:

    name: Build Code Base
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: gladostek
        password: dckr_pat_z1Tqr1UKRAEp-3eAIhF1W8LkXYg
        
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build
      run: |
        sudo apt update
        sudo apt install apt-transport-https curl gnupg-agent ca-certificates software-properties-common -y
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        sudo apt install docker-ce docker-ce-cli containerd.io -y
        sudo docker build -f Dockerfile.test -t glados .
      shell: sh

    - name: Tests
      run: |
        sudo docker run glados
        
    - name: Create Unit Tests Artifact
      uses: actions/upload-artifact@v3
      with:
        name: unit_tests_res
        path: unit_tests_res
